openapi: 3.1.0
info:
  title: Django API
  description: Sofware Testing Django REST API.
servers:
  - url: http://127.0.0.1:8000/datatb/
paths:
  /product/add/:
    post:
      summary: Adding data table
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                info:
                  type: string
                price:
                  type: string
              required:
                - username
                - email
            examples:
              default_example:
                value:
                  name: chicken
                  info: abcd
                  price: 10
      responses:
        '200':
          description: Listing added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    id: int
                    message: string
                    success: bool
              examples:
                default_example:
                  value:
                    id: User created successfully
                    message: Record Created.
                    success: true
